# Generated by Django 2.1.7 on 2019-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('couno', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('serno', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuno', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('stuname', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
