# Generated by Django 2.1.7 on 2019-09-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicineopendata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(blank=True, db_column='ch-name', max_length=500, null=True)),
                ('en_name', models.CharField(blank=True, db_column='en-name', max_length=500, null=True)),
                ('indication', models.CharField(blank=True, max_length=2000, null=True)),
                ('component', models.CharField(blank=True, max_length=2000, null=True)),
                ('formulation', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'medicineopendata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_message',
                'managed': False,
            },
        ),
    ]
